name: Issue Opend
on:
  issues:
    types: opened

jobs:
  issue_opend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Opend
        uses: ./actions/issue_opend
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
