name: Issue Connected
on:
  issues:
    types: edited

jobs:
  issue_connected:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Connected
        uses: ./actions/issue_connected
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
