name: Issue Opend
on:
  issues:
    types: opened

jobs:
  issue_opend:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      ISSUE_NUM: ${{ github.event.issue.number }}
    permissions:
      id-token: write
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Opend
        uses: ./actions/issue_opend
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
      - name: Create files
        run: |
          mkdir $ISSUE_NUM
          echo -e "こんにちは、CX事業本部 IoT事業部の若槻です。\n\n今回は、${ISSUE_TITLE}\n\n## おわりに\n\n\n\n## 参考\n\n\n\n以上" \
            >> $ISSUE_NUM/article.md
      - name: Create branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ github.event.issue.title }}
      - name: Create PR
        run: |
          gh pr create \
            --head $NEW_BRANCH_NAME \
            --base $BASE_BRANCH_NAME \
            --title "$ISSUE_TITLE" \
            --body "close #${ISSUE_NUM}"
        env:
          NEW_BRANCH_NAME: ${{ github.event.issue.title }}
          BASE_BRANCH_NAME: ${{ github.event.repository.default_branch }}
