name: Action Sample
on:
  issues:
    types: [opened]
  label:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: execute echo command
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.issue.number }}
      - name: excute js
        uses: ./actions/issue_create # Uses an action in the root directory
