name: Issue Opend
on:
  issues:
    types: [opened, labeled]

jobs:
  issue_opend:
    runs-on: ubuntu-latest
    steps:
      - name: check label
        run: |
          echo ${{ github.event.issue.label.name }}
          exit 1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Opend
        uses: ./actions/issue_opend
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
