name: Action Sample
on:
  issues:
    types: [assigned]
  label:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: excute js
        uses: ./actions/issue_assigned # Uses an action in the root directory
