name: Issue Assigned
on:
  issues:
    types: [assigned]
  label:

jobs:
  issue_assigned:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Assigned
        uses: ./actions/issue_assigned
