name: Issue Connected
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  issue_opend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Issue Connected
        uses: ./actions/issue_connected
