name: Task Opend
on:
  issues:
    types: [opened]
  label:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Task Opend
        uses: ./actions/issue_opend # Uses an action in the root directory
