name: Action Sample
on:
  issues:
    types: [opened]
  label:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.issue.number }}
          echo ${{ github.event.issue.comment }}
